{
 "title": "BRI KUBERNETES ALL NODES",
 "description": "Dashboard to get an overview of all nodes in a Kubernetes Cluster",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "vonage-status-panel",
   "description": "Master 1 Nodes Status.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregation": "Sum",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{instance=\"kube-master01\",job=\"kubernetes-nodes\"}",
     "units": "none",
     "url": "sum(node_cpu{app=\"prometheus\",component=\"node-exporter\", instance=\"172.18.82.22:9100\"})",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "description": "Master 2 Nodes Status.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "aggregation": "Sum",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{instance=\"kube-master02\",job=\"kubernetes-nodes\"}",
     "units": "none",
     "url": "sum(node_cpu{app=\"prometheus\",component=\"node-exporter\", instance=\"172.18.82.22:9100\"})",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "description": "Master 3 Nodes Status.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "aggregation": "Sum",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{instance=\"kube-master03\",job=\"kubernetes-nodes\"}",
     "units": "none",
     "url": "sum(node_cpu{app=\"prometheus\",component=\"node-exporter\", instance=\"172.18.82.22:9100\"})",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "description": "Worker 1 Nodes Status.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "aggregation": "Sum",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{instance=\"kube-worker01\",job=\"kubernetes-nodes\"}",
     "units": "none",
     "url": "sum(node_cpu{app=\"prometheus\",component=\"node-exporter\", instance=\"172.18.82.22:9100\"})",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "description": "Worker 2 Nodes Status.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "aggregation": "Sum",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{instance=\"kube-worker02\",job=\"kubernetes-nodes\"}",
     "units": "none",
     "url": "sum(node_cpu{app=\"prometheus\",component=\"node-exporter\", instance=\"172.18.82.22:9100\"})",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "description": "Worker 3 Nodes Status.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "aggregation": "Sum",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{instance=\"kube-worker03\",job=\"kubernetes-nodes\"}",
     "units": "none",
     "url": "sum(node_cpu{app=\"prometheus\",component=\"node-exporter\", instance=\"172.18.82.22:9100\"})",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Idle cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode=\"idle\"}[2m])) * 100 / count(node_cpu{mode=\"idle\"})",
     "legendFormat": "Sum Idle CPU"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal)) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_ms[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}