{
 "title": "BRI KUBERNETES WORKER 1",
 "description": "Dashboard to get an overview of all nodes in a Kubernetes Cluster",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "vonage-status-panel",
   "description": "Worker 1 Nodes Status.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregation": "Sum",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "up{instance=\"kube-worker01\",job=\"kubernetes-nodes\"}",
     "units": "none",
     "url": "sum(node_cpu{app=\"prometheus\",component=\"node-exporter\", instance=\"172.18.82.22:9100\"})",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Idle cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{instance=\"172.18.82.22:9100\", mode=\"idle\"}[2m])) * 100 / count(node_cpu{instance=\"172.18.82.22:9100\", mode=\"idle\"})",
     "legendFormat": "Idle CPU"
    },
    {}
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "sum(node_load5{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "sum(node_load15{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"}) - sum(node_memory_MemFree{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"}) - sum(\nnode_memory_Buffers{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"}) - sum(node_memory_Cached{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})",
     "legendFormat": "memory usage"
    },
    {
     "expr": "sum(node_memory_Buffers{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "sum(node_memory_Cached{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "sum(node_memory_MemFree{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"}) - sum(node_memory_MemFree{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"}) - sum(node_memory_Buffers{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"}) - sum(node_memory_Cached{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})) / sum(node_memory_MemTotal{app=\"prometheus\",component=\"node-exporter\",instance=\"172.18.82.22:9100\",job=\"kubernetes-endpoints\",kubernetes_name=\"prometheus-node-exporter\",kubernetes_namespace=\"monitoring\"})) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read{app=\"prometheus\",instance=\"172.18.82.22:9100\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written{app=\"prometheus\",instance=\"172.18.82.22:9100\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_ms{app=\"prometheus\", instance=\"172.18.82.22:9100\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\", instance=\"172.18.82.22:9100\"}) - sum(node_filesystem_free{device!=\"rootfs\", instance=\"172.18.82.22:9100\"})) / sum(node_filesystem_size{device!=\"rootfs\", instance=\"172.18.82.22:9100\"})"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{instance=\"172.18.82.22:9100\", device!~\"lo\"}[5m]))",
     "legendFormat": "Network Received"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{instance=\"172.18.82.22:9100\", device!~\"lo\"}[5m]))",
     "legendFormat": "Network Transmitted"
    }
   ]
  }
 ]
}